### HTTP Request
GET http://localhost:3000/users

### Crear un nuevo usuario (POST)
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Ulises"
}

### Obtener un usuario específico por ID (GET individual)
GET http://localhost:3000/users/3

### Eliminar un usuario (DELETE)
DELETE http://localhost:3000/users/3