### HTTP Request

### REGISTRAR NUEVO USUARIO 
POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "ulises_NO_user",
    "email": "ulises_NO_user@correo.com",
    "password": "mi-clave-segura",
    "role": "no-user"
}

### HACER LOGIN 
# @name login
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "ulises_NO_user",
  "password": "mi-clave-segura"
}


### VER LISTA DE USUARIOS (Usa el token dinámico del paso anterior para la autorización)
GET http://localhost:3000/users
Authorization: Bearer {{login.response.body.authorizationToken}}

###
PATCH http://localhost:3000/users/ulises_NO_user
Content-Type: application/json
{
    "username": "ulises_NO_user",
    "email": "ulises_NO_user_EDITADO@correo.com"
}

###
DELETE http://localhost:3000/users/ulises_NO_user









### OTROS EJEMPLOS DE PETICIONES
GET http://localhost:3000/users

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "Luciano",
    "email": "maldito@gmail.com"
}

### 
POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "Ermac",
    "email": "ulisesgabriel@gmail.com"
}

###
PATCH http://localhost:3000/users/Ulises
Content-Type: application/json

{
    "username": "Prueba",
    "email": "prueba@gmail.com"
}

### 
GET http://localhost:3000/users/Ulises

### 
DELETE http://localhost:3000/users/Ermac